import { Link, useLocation } from 'react-router'

const pages: Record<string, { eyebrow: string; title: string; intro: string; sections: Array<[string, string]> }> = {
  about: { eyebrow: 'Câu chuyện HORIZ', title: 'Chuyển động tự nhiên, thiết kế có chủ đích.', intro: 'HORIZ tạo ra những sản phẩm tối giản, linh hoạt và dễ sống cùng mỗi ngày.', sections: [['Điều chúng tôi theo đuổi', 'Một đôi giày tốt không cần gây chú ý. Nó cần vừa vặn, bền bỉ và giúp bạn đi qua ngày dài một cách tự nhiên.'], ['Cách chúng tôi thiết kế', 'Mỗi chi tiết được cân nhắc theo ba tiêu chí: thoải mái thực tế, hình dáng lâu bền và vật liệu phù hợp với công năng.']] },
  materials: { eyebrow: 'Vật liệu', title: 'Ít hơn, nhưng đúng hơn.', intro: 'Chúng tôi ưu tiên vật liệu tự nhiên và tái chế khi chúng thực sự cải thiện trải nghiệm sử dụng.', sections: [['Len Merino', 'Điều hòa nhiệt, mềm và phù hợp với nhiều điều kiện thời tiết.'], ['Sợi cây', 'Nhẹ, thoáng và mang lại cảm giác mát cho những ngày di chuyển nhiều.'], ['Vật liệu tái chế', 'Được sử dụng có chọn lọc ở dây giày, lớp lót và bao bì để giảm vật liệu nguyên sinh.']] },
  help: { eyebrow: 'Hỗ trợ', title: 'Chúng tôi có thể giúp gì?', intro: 'Bạn có thể liên hệ đội ngũ HORIZ trong giờ làm việc từ 09:00 đến 18:00, thứ Hai đến thứ Bảy.', sections: [['Đơn hàng', 'Gửi email support@horiz.vn kèm mã đơn hàng để được kiểm tra nhanh.'], ['Chọn kích thước', 'Đo chiều dài bàn chân vào cuối ngày và đối chiếu bảng size trên từng trang sản phẩm.'], ['Liên hệ', 'Email: support@horiz.vn · Hotline: 1900 6868.']] },
  returns: { eyebrow: 'Đổi trả', title: 'Đổi trả rõ ràng trong 30 ngày.', intro: 'Sản phẩm chưa qua sử dụng, còn nguyên tem và hộp có thể yêu cầu đổi trả trong vòng 30 ngày kể từ khi nhận hàng.', sections: [['Điều kiện áp dụng', 'Sản phẩm sạch, chưa giặt, không có dấu hiệu sử dụng và còn đầy đủ phụ kiện đi kèm.'], ['Quy trình', 'Liên hệ hỗ trợ với mã đơn; chúng tôi xác nhận yêu cầu và hướng dẫn gửi trả.'], ['Hoàn tiền', 'Khoản hoàn được xử lý sau khi sản phẩm được kiểm tra, theo phương thức thanh toán ban đầu khi có thể.']] },
  privacy: { eyebrow: 'Pháp lý', title: 'Chính sách quyền riêng tư', intro: 'HORIZ chỉ thu thập dữ liệu cần thiết để xử lý đơn hàng, hỗ trợ khách hàng và cải thiện dịch vụ.', sections: [['Dữ liệu sử dụng', 'Thông tin liên hệ, địa chỉ và lịch sử đơn hàng được dùng để hoàn tất giao dịch và hỗ trợ sau bán.'], ['Bảo mật', 'Quyền truy cập dữ liệu được giới hạn theo vai trò và các thao tác quản trị được ghi nhận.'], ['Quyền của bạn', 'Bạn có thể yêu cầu xem, sửa hoặc xóa thông tin cá nhân theo quy định áp dụng.']] },
  terms: { eyebrow: 'Pháp lý', title: 'Điều khoản sử dụng', intro: 'Khi đặt hàng, bạn xác nhận thông tin cung cấp là chính xác và đồng ý với chính sách bán hàng hiện hành.', sections: [['Giá và tồn kho', 'Giá, ưu đãi và tồn kho được xác nhận lại tại thời điểm đặt hàng.'], ['Thanh toán COD', 'Khách hàng thanh toán cho đơn vị vận chuyển khi nhận hàng.'], ['Giới hạn trách nhiệm', 'HORIZ xử lý khiếu nại theo pháp luật Việt Nam và chính sách công bố tại thời điểm mua.']] },
}

export function StaticContentPage() {
  const key = useLocation().pathname.slice(1)
  const page = pages[key] ?? pages.help!
  return <main className="content-page" id="main-content"><header><p className="ab-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></header><div className="content-page__sections">{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div>{key === 'help' ? <Link className="button button--primary" to="/search">Tìm sản phẩm</Link> : null}</main>
}
