create schema if not exists private;

create type public.app_role as enum ('customer', 'staff', 'admin');
create type public.member_state as enum ('active', 'blocked');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.app_role not null default 'customer',
  granted_by uuid references auth.users (id) on delete set null,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.member_status (
  user_id uuid primary key references auth.users (id) on delete cascade,
  status public.member_state not null default 'active',
  reason text,
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now()
);

create index profiles_created_at_idx on public.profiles (created_at desc);
create index user_roles_user_id_active_idx on public.user_roles (user_id) where revoked_at is null;
create unique index user_roles_active_role_unique
  on public.user_roles (user_id, role)
  where revoked_at is null;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.member_status enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.user_roles from anon, authenticated;
revoke all on table public.member_status from anon, authenticated;

grant select, update on table public.profiles to authenticated;
grant select on table public.user_roles to authenticated;
grant select on table public.member_status to authenticated;

create policy "Members can read their own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "Members can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Members can read their own active role"
on public.user_roles for select
to authenticated
using ((select auth.uid()) = user_id and revoked_at is null);

create policy "Members can read their own status"
on public.member_status for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id);
  insert into public.user_roles (user_id, role) values (new.id, 'customer');
  insert into public.member_status (user_id, status) values (new.id, 'active');
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure private.handle_new_user();
